[server]
host = "127.0.0.1"
port = 3000

[service]
name = "mp-playground"
greeting = "Hello from ${service.name}"

[logging]
filter = "info,mp_playground=debug"
format = "compact"
target = true
thread-ids = false
thread-names = false
file = false
line-number = false
ansi = true

[fault-tolerance]
timeout = "250ms"
max-retries = 2
retry-delay = "25ms"
bulkhead-size = 4
circuit-request-volume = 4
circuit-failure-ratio = 0.5
circuit-delay = "1500ms"
